services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: "Europe/Warsaw"
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/posgresql/data