services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      PGDATA: /pg-data
      TZ: "Europe/Warsaw"
    ports:
      - '5432:5432'
    volumes:
      - ./pg-data:/pg-data
volumes:
  pgdata: