services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: e-commerce
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - '5432:5432'
    volumes:
      - e-commerce-data:/var/lib/postgresql/data
volumes:
  e-commerce-data: