spring:
  datasource:
    url: jdbc:postgres://localhost:5432/e-commerce
  security:
    user:
      name: user
      password: pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false
    enabled: true
    locations: classpath:/db/migration, classpath:/db/test-data

  docker:
    compose:
      skip:
        in-tests: false

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    pl:
      dk: TRACE
    org:
      flywaydb: TRACE
      hibernate:
        orm:
          jdbc:
            bind: TRACE

server:
  error:
    include-message: always

jws:
  sharedKey: ${JWS_SHARED_KEY}

stripe:
  api:
    key: ${STRIPE_API_KEY}
  webhook:
    key: ${STRIPE_WEBHOOK_KEY}



