spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    locations: classpath:/db/migration, classpath:/db/init-data

  docker:
    compose:
      enabled: true
      stop:
        command: down
