spring:
  datasource:
    url: jdbc:postgres://localhost:5432/e-commerce

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    clean-disabled: false
    enabled: true
    locations: classpath:/db/migration, classpath:/db/test-data

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      flywaydb: TRACE
      hibernate:
        orm:
          jdbc:
            bind: TRACE