name: Build and Deploy
on:
  push:
    branches:
      - Feature/github
jobs:
  build-deploy:
    name: Build and Deploy e-commerce-platform
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      EMAIL: ${{ secrets.EMAIL }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      JWS_SHARED_KEY: ${{ secrets.JWS_SHARED_KEY }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      STRIPE_WEBHOOK_KEY: ${{ secrets.STRIPE_WEBHOOK_KEY }}
    steps:
      #-----------------------------------------------------------------------------------------------------------------------
      - name: Checkout code
        uses: actions/checkout@v4
      #-----------------------------------------------------------------------------------------------------------------------
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      #-----------------------------------------------------------------------------------------------------------------------
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      #-----------------------------------------------------------------------------------------------------------------------
      - name: Unit & Integration tests
        run: mvn -B test -Dspring.profiles.active=test

      - name: Build application
        run: |
          mvn clean --file pom.xml
          mvn -B package -DskipTest --file pom.xml

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/e-commerce-platform:latest